Repository alarmfox/game-repository, pull requests merged in 2023-05, with the labels that each got.

#39 Refactoring: merged storage in service.
  controller.go
  controller_test.go
  dto.go
  main.go
  model.go
  service.go
  storage.go
  utils.go
Labels: development

#43 Feat/bulk turn creation
  controller.go
  controller_test.go
  dto.go
  model.go
  service.go
  utils.go
Labels: development

#41 Feat/cleanup job
  go.mod
  go.sum
  main.go
  main_test.go
  model.go
  service.go
  vendor/golang.org/x/sync/LICENSE
  vendor/golang.org/x/sync/PATENTS
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/modules.txt
Labels: development

#47 Updated descrption
  postman/schemas/index.yaml
Labels: development

#48 Added duplicated check
  service.go
Labels: bug, development

#63 Refactoring
  .github/workflows/go.yml
  Makefile
  README.md
  api/errors.go
  api/game/controller.go
  api/game/controller_test.go
  api/game/game.go
  api/game/service.go
  api/http.go
  api/robot/controller.go
  api/robot/controller_test.go
  api/robot/robot.go
  api/robot/service.go
  api/round/controller.go
  api/round/controller_test.go
  api/round/round.go
  api/round/service.go
  api/turn/controller.go
  api/turn/controller_test.go
  api/turn/service.go
  api/turn/service_test.go
  api/turn/turn.go
  api/utils.go
  main.go
  web/robot/controller_test.go
Labels: documentation, design, development

#65 Feat/find game by player
  .air.toml
  Makefile
  README.md
  api/game/controller.go
  api/game/controller_test.go
  api/game/game.go
  api/game/service.go
  api/round/round.go
  api/round/service.go
  api/turn/service.go
  api/turn/turn.go
  go.mod
  main.go
  model/model.go
  postman/schemas/index.yaml
Labels: development
